### ISSUE TITLE
Customize the address bar

### ISSUE THREAD

**Issue by CoverageCraft** [PROxZIMA/Firefox-Theme#2]
Is there any way to make the address bar longer?

![image](https://user-images.githubusercontent.com/67969086/108616176-7a093300-7424-11eb-9c2e-3f68db34c8bd.png)

**Comment by PROxZIMA** [comment]
Look for following in `userChrome.css`
```
/* Move tabs 35% to right */
#TabsToolbar {
    margin-left: 32vw !important;
    width: 68vw !important;
}

/* Move navigation 65% to left and negative margin to move to top line */
#nav-bar {
    max-height: 28px !important;
    margin-right: 68vw !important;
    margin-top: -28px !important;
    width: 32vw !important;
    background: transparent !important;
    z-index: 1;
}
```
Here `margin-left` under `TabsToolbar` & `margin-right` under `nav-bar` is what you need to edit. If you increase one then make sure to decrease the other so that they both sum up to `100`.
`x vw` means x% of viewport's(screen) width. So increase `margin-left` to increase address bar size
